package com.model;

/**
 * TAllusers generated by MyEclipse Persistence Tools
 */

public class TAllusers implements java.io.Serializable {

	// Fields

	private Integer id;

	private String username;
	private String pwd;
	private String cx;
	private String addtime;
	// Constructors

	/** default constructor */
	public TAllusers() {
	}

	

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	
	public String getCx() {
		return this.cx;
	}

	public void setCx(String cx) {
		this.cx = cx;
	}

	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}