package com.model;

/**
 * TDaibanshiyi generated by MyEclipse Persistence Tools
 */

public class TDaibanshiyi implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String shixiangbianhao;	private String shixiangmingcheng;	private String daibanriqi;	private String neirong;	private String zhuangtai;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TDaibanshiyi()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getShixiangbianhao()
	{
		return shixiangbianhao;
	}
	public void setShixiangbianhao(String shixiangbianhao)
	{
		this.shixiangbianhao = shixiangbianhao;
	}		public String getShixiangmingcheng()
	{
		return shixiangmingcheng;
	}
	public void setShixiangmingcheng(String shixiangmingcheng)
	{
		this.shixiangmingcheng = shixiangmingcheng;
	}		public String getDaibanriqi()
	{
		return daibanriqi;
	}
	public void setDaibanriqi(String daibanriqi)
	{
		this.daibanriqi = daibanriqi;
	}		public String getNeirong()
	{
		return neirong;
	}
	public void setNeirong(String neirong)
	{
		this.neirong = neirong;
	}		public String getZhuangtai()
	{
		return zhuangtai;
	}
	public void setZhuangtai(String zhuangtai)
	{
		this.zhuangtai = zhuangtai;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
