package com.model;

/**
 * TGouzhijihua generated by MyEclipse Persistence Tools
 */

public class TGouzhijihua implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String jihuadanhao;	private String jihuamingcheng;	private String gouzhineirong;	private String yugufeiyong;	private String shenqingren;	private String issh;	private String shhf;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TGouzhijihua()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getJihuadanhao()
	{
		return jihuadanhao;
	}
	public void setJihuadanhao(String jihuadanhao)
	{
		this.jihuadanhao = jihuadanhao;
	}		public String getJihuamingcheng()
	{
		return jihuamingcheng;
	}
	public void setJihuamingcheng(String jihuamingcheng)
	{
		this.jihuamingcheng = jihuamingcheng;
	}		public String getGouzhineirong()
	{
		return gouzhineirong;
	}
	public void setGouzhineirong(String gouzhineirong)
	{
		this.gouzhineirong = gouzhineirong;
	}		public String getYugufeiyong()
	{
		return yugufeiyong;
	}
	public void setYugufeiyong(String yugufeiyong)
	{
		this.yugufeiyong = yugufeiyong;
	}		public String getShenqingren()
	{
		return shenqingren;
	}
	public void setShenqingren(String shenqingren)
	{
		this.shenqingren = shenqingren;
	}	
	
		public String getIssh()
	{
		return issh;
	}
	public void setIssh(String issh)
	{
		this.issh = issh;
	}		public String getShhf()
	{
		return shhf;
	}
	public void setShhf(String shhf)
	{
		this.shhf = shhf;
	}	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
