package com.model;

/**
 * TJianxiuzhouqi generated by MyEclipse Persistence Tools
 */

public class TJianxiuzhouqi implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String shebeibianhao;	private String shebeimingcheng;	private String shebeileixing;	private String jianxiuriqi;	private String guzhangmiaoshu;	private String yanzhongchengdu;	private String jianxiufeiyong;	private String fuzeren;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TJianxiuzhouqi()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getShebeibianhao()
	{
		return shebeibianhao;
	}
	public void setShebeibianhao(String shebeibianhao)
	{
		this.shebeibianhao = shebeibianhao;
	}		public String getShebeimingcheng()
	{
		return shebeimingcheng;
	}
	public void setShebeimingcheng(String shebeimingcheng)
	{
		this.shebeimingcheng = shebeimingcheng;
	}		public String getShebeileixing()
	{
		return shebeileixing;
	}
	public void setShebeileixing(String shebeileixing)
	{
		this.shebeileixing = shebeileixing;
	}		public String getJianxiuriqi()
	{
		return jianxiuriqi;
	}
	public void setJianxiuriqi(String jianxiuriqi)
	{
		this.jianxiuriqi = jianxiuriqi;
	}		public String getGuzhangmiaoshu()
	{
		return guzhangmiaoshu;
	}
	public void setGuzhangmiaoshu(String guzhangmiaoshu)
	{
		this.guzhangmiaoshu = guzhangmiaoshu;
	}		public String getYanzhongchengdu()
	{
		return yanzhongchengdu;
	}
	public void setYanzhongchengdu(String yanzhongchengdu)
	{
		this.yanzhongchengdu = yanzhongchengdu;
	}		public String getJianxiufeiyong()
	{
		return jianxiufeiyong;
	}
	public void setJianxiufeiyong(String jianxiufeiyong)
	{
		this.jianxiufeiyong = jianxiufeiyong;
	}		public String getFuzeren()
	{
		return fuzeren;
	}
	public void setFuzeren(String fuzeren)
	{
		this.fuzeren = fuzeren;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
