package com.model;

/**
 * TJishutuzhi generated by MyEclipse Persistence Tools
 */

public class TJishutuzhi implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String tuzhibianhao;	private String tuzhimingcheng;	private String tuzhiwenjian;	private String shejishi;	private String beizhu;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TJishutuzhi()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getTuzhibianhao()
	{
		return tuzhibianhao;
	}
	public void setTuzhibianhao(String tuzhibianhao)
	{
		this.tuzhibianhao = tuzhibianhao;
	}		public String getTuzhimingcheng()
	{
		return tuzhimingcheng;
	}
	public void setTuzhimingcheng(String tuzhimingcheng)
	{
		this.tuzhimingcheng = tuzhimingcheng;
	}		public String getTuzhiwenjian()
	{
		return tuzhiwenjian;
	}
	public void setTuzhiwenjian(String tuzhiwenjian)
	{
		this.tuzhiwenjian = tuzhiwenjian;
	}		public String getShejishi()
	{
		return shejishi;
	}
	public void setShejishi(String shejishi)
	{
		this.shejishi = shejishi;
	}		public String getBeizhu()
	{
		return beizhu;
	}
	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
