package com.model;

/**
 * TLiuyanban generated by MyEclipse Persistence Tools
 */

public class TLiuyanban implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String cheng;	private String xingbie;	private String QQ;	private String youxiang;	private String dianhua;	private String neirong;	private String huifuneirong;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TLiuyanban()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getCheng()
	{
		return cheng;
	}
	public void setCheng(String cheng)
	{
		this.cheng = cheng;
	}		public String getXingbie()
	{
		return xingbie;
	}
	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}		public String getQQ()
	{
		return QQ;
	}
	public void setQQ(String QQ)
	{
		this.QQ = QQ;
	}		public String getYouxiang()
	{
		return youxiang;
	}
	public void setYouxiang(String youxiang)
	{
		this.youxiang = youxiang;
	}		public String getDianhua()
	{
		return dianhua;
	}
	public void setDianhua(String dianhua)
	{
		this.dianhua = dianhua;
	}		public String getNeirong()
	{
		return neirong;
	}
	public void setNeirong(String neirong)
	{
		this.neirong = neirong;
	}		public String getHuifuneirong()
	{
		return huifuneirong;
	}
	public void setHuifuneirong(String huifuneirong)
	{
		this.huifuneirong = huifuneirong;
	}	
	
	//yoxushexnhe
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
