package com.model;

/**
 * TPinglun generated by MyEclipse Persistence Tools
 */

public class TPinglun implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String xinwenID;	private String pinglunneirong;	private String pinglunren;	private String pingfen;	private String biao;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TPinglun()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getXinwenID()
	{
		return xinwenID;
	}
	public void setXinwenID(String xinwenID)
	{
		this.xinwenID = xinwenID;
	}		public String getPinglunneirong()
	{
		return pinglunneirong;
	}
	public void setPinglunneirong(String pinglunneirong)
	{
		this.pinglunneirong = pinglunneirong;
	}		public String getPinglunren()
	{
		return pinglunren;
	}
	public void setPinglunren(String pinglunren)
	{
		this.pinglunren = pinglunren;
	}		public String getPingfen()
	{
		return pingfen;
	}
	public void setPingfen(String pingfen)
	{
		this.pingfen = pingfen;
	}		public String getBiao()
	{
		return biao;
	}
	public void setBiao(String biao)
	{
		this.biao = biao;
	}	
	
	//yoxushexnhe
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
