package com.model;

/**
 * TShebeixinxi generated by MyEclipse Persistence Tools
 */

public class TShebeixinxi implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String shebeibianhao;	private String shebeimingcheng;	private String shebeileixing;	private String gouzhiriqi;	private String zhaopian;	private String gouzhijiage;	private String zhifangdidian;	private String xinjiuchengdu;	private String beizhu;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TShebeixinxi()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getShebeibianhao()
	{
		return shebeibianhao;
	}
	public void setShebeibianhao(String shebeibianhao)
	{
		this.shebeibianhao = shebeibianhao;
	}		public String getShebeimingcheng()
	{
		return shebeimingcheng;
	}
	public void setShebeimingcheng(String shebeimingcheng)
	{
		this.shebeimingcheng = shebeimingcheng;
	}		public String getShebeileixing()
	{
		return shebeileixing;
	}
	public void setShebeileixing(String shebeileixing)
	{
		this.shebeileixing = shebeileixing;
	}		public String getGouzhiriqi()
	{
		return gouzhiriqi;
	}
	public void setGouzhiriqi(String gouzhiriqi)
	{
		this.gouzhiriqi = gouzhiriqi;
	}		public String getZhaopian()
	{
		return zhaopian;
	}
	public void setZhaopian(String zhaopian)
	{
		this.zhaopian = zhaopian;
	}		public String getGouzhijiage()
	{
		return gouzhijiage;
	}
	public void setGouzhijiage(String gouzhijiage)
	{
		this.gouzhijiage = gouzhijiage;
	}		public String getZhifangdidian()
	{
		return zhifangdidian;
	}
	public void setZhifangdidian(String zhifangdidian)
	{
		this.zhifangdidian = zhifangdidian;
	}		public String getXinjiuchengdu()
	{
		return xinjiuchengdu;
	}
	public void setXinjiuchengdu(String xinjiuchengdu)
	{
		this.xinjiuchengdu = xinjiuchengdu;
	}		public String getBeizhu()
	{
		return beizhu;
	}
	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
