package com.model;

/**
 * TXinwentongzhi generated by MyEclipse Persistence Tools
 */

public class TXinwentongzhi implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String biaoti;	private String leibie;	private String neirong;	private String shouyetupian;	private String dianjilv;	private String tianjiaren;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TXinwentongzhi()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getBiaoti()
	{
		return biaoti;
	}
	public void setBiaoti(String biaoti)
	{
		this.biaoti = biaoti;
	}		public String getLeibie()
	{
		return leibie;
	}
	public void setLeibie(String leibie)
	{
		this.leibie = leibie;
	}		public String getNeirong()
	{
		return neirong;
	}
	public void setNeirong(String neirong)
	{
		this.neirong = neirong;
	}		public String getShouyetupian()
	{
		return shouyetupian;
	}
	public void setShouyetupian(String shouyetupian)
	{
		this.shouyetupian = shouyetupian;
	}		public String getDianjilv()
	{
		return dianjilv;
	}
	public void setDianjilv(String dianjilv)
	{
		this.dianjilv = dianjilv;
	}		public String getTianjiaren()
	{
		return tianjiaren;
	}
	public void setTianjiaren(String tianjiaren)
	{
		this.tianjiaren = tianjiaren;
	}	
	
	//yoxushexnhe
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
