package com.model;

/**
 * TYonghuzhuce generated by MyEclipse Persistence Tools
 */

public class TYonghuzhuce implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String yonghuming;	private String mima;	private String xingming;	private String xingbie;	private String chushengnianyue;	private String qq;	private String youxiang;	private String dianhua;	private String shenfenzheng;	private String touxiang;	private String dizhi;	private String beizhu;	private String issh;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TYonghuzhuce()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getYonghuming()
	{
		return yonghuming;
	}
	public void setYonghuming(String yonghuming)
	{
		this.yonghuming = yonghuming;
	}		public String getMima()
	{
		return mima;
	}
	public void setMima(String mima)
	{
		this.mima = mima;
	}		public String getXingming()
	{
		return xingming;
	}
	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}		public String getXingbie()
	{
		return xingbie;
	}
	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}		public String getChushengnianyue()
	{
		return chushengnianyue;
	}
	public void setChushengnianyue(String chushengnianyue)
	{
		this.chushengnianyue = chushengnianyue;
	}		public String getQq()
	{
		return qq;
	}
	public void setQq(String qq)
	{
		this.qq = qq;
	}		public String getYouxiang()
	{
		return youxiang;
	}
	public void setYouxiang(String youxiang)
	{
		this.youxiang = youxiang;
	}		public String getDianhua()
	{
		return dianhua;
	}
	public void setDianhua(String dianhua)
	{
		this.dianhua = dianhua;
	}		public String getShenfenzheng()
	{
		return shenfenzheng;
	}
	public void setShenfenzheng(String shenfenzheng)
	{
		this.shenfenzheng = shenfenzheng;
	}		public String getTouxiang()
	{
		return touxiang;
	}
	public void setTouxiang(String touxiang)
	{
		this.touxiang = touxiang;
	}		public String getDizhi()
	{
		return dizhi;
	}
	public void setDizhi(String dizhi)
	{
		this.dizhi = dizhi;
	}		public String getBeizhu()
	{
		return beizhu;
	}
	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}	
	
		public String getIssh()
	{
		return issh;
	}
	public void setIssh(String issh)
	{
		this.issh = issh;
	}
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
