package com.model;

/**
 * TYuangongxinxi generated by MyEclipse Persistence Tools
 */

public class TYuangongxinxi implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String gonghao;	private String mima;	private String xingming;	private String xingbie;	private String shenfenzheng;	private String dianhua;	private String bumen;	private String zhaopian;	private String jibenyuexin;	private String beizhu;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TYuangongxinxi()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getGonghao()
	{
		return gonghao;
	}
	public void setGonghao(String gonghao)
	{
		this.gonghao = gonghao;
	}		public String getMima()
	{
		return mima;
	}
	public void setMima(String mima)
	{
		this.mima = mima;
	}		public String getXingming()
	{
		return xingming;
	}
	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}		public String getXingbie()
	{
		return xingbie;
	}
	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}		public String getShenfenzheng()
	{
		return shenfenzheng;
	}
	public void setShenfenzheng(String shenfenzheng)
	{
		this.shenfenzheng = shenfenzheng;
	}		public String getDianhua()
	{
		return dianhua;
	}
	public void setDianhua(String dianhua)
	{
		this.dianhua = dianhua;
	}		public String getBumen()
	{
		return bumen;
	}
	public void setBumen(String bumen)
	{
		this.bumen = bumen;
	}		public String getZhaopian()
	{
		return zhaopian;
	}
	public void setZhaopian(String zhaopian)
	{
		this.zhaopian = zhaopian;
	}		public String getJibenyuexin()
	{
		return jibenyuexin;
	}
	public void setJibenyuexin(String jibenyuexin)
	{
		this.jibenyuexin = jibenyuexin;
	}		public String getBeizhu()
	{
		return beizhu;
	}
	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
